### ISSUE TITLE
Refactoring tracking and checking tutorials and workflows - high priority for next release.

### ISSUE THREAD

**Issue by Garyfallidis** [dipy/dipy#1501]
We need to look carefully to our tracking framework and refactor some of the cython parts as well as improve tutorials and add workflows. I suggest this being high priority for release 0.15. Let me know if you agree and have suggestions for improvements.

As discussed in #1786 (DIPY LAB) we need to:

- [ ] Change local tracking with initial directions. This change will change current behavior of LocalTracker.
- [ ] Test EuDX, PFT and Bootstrap trackers (build workflows) with data and quality control them (dipy_qa). 
- [ ] All should be ready for July release.
- [x] Discuss in the next meeting
- [x] Remove legacy code and examples 
- [ ] #1648 Mesh seeding to be rebased after changes, as well as #1635.

**Comment by gabknight** [comment]
yes! With 2 large PR + a cython refactoring, that would a good to do some tweaks now. We have to push the workflows for all the various tracking algorithm for 0.15!

**Comment by jchoude** [comment]
Might this be a good opportunity to uniformize the streamlines handling, with @frheault and what was discussed at the Workshop?
